using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;

namespace AWSTranscriberAPI.Models
{
    public class Transcription
    {
        public int version { get; set; }
        public string file { get; set; }
        public string action { get; set; }
        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
    }

    public class Media
    {
        public int version { get; set; }
        public string file { get; set; }
        public int length { get; set; }
        public int position { get; set; }
        public string state { get; set; }
        public string assignedTo { get; set; }
        public List<Transcription> transcription { get; set; }
    }
    public class NewTask
    {
        public string taskID { get; set; }
        public string name { get; set; }
        public string passageSet { get; set; }
        public string book { get; set; }
        public string description { get; set; }
        //public List<Media> audio { get; set; }
    }
    public class TransTask
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId _id { get; set; }
        public string taskID { get; set; }
        public string name { get; set; }
        public string passageSet { get; set; }
        public string book { get; set; }
        public string description { get; set; }
        //public List<Media> audio { get; set; }
    }
}